// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4lhsmEH8OQWlkUfSR0a3jvY0_EHiXEiA',
    appId: '1:846053857270:web:d2ba3637824325d5e519d7',
    messagingSenderId: '846053857270',
    projectId: 'cozkazan-app',
    authDomain: 'cozkazan-app.firebaseapp.com',
    storageBucket: 'cozkazan-app.firebasestorage.app',
    measurementId: 'G-DZ0NNZHW7S',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    appId: '1:846053857270:ios:XXXXXXXXXXXXXXXXXXXX',
    messagingSenderId: '846053857270',
    projectId: 'cozkazan-app',
    storageBucket: 'cozkazan-app.appspot.com',
    iosClientId: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.apps.googleusercontent.com',
    iosBundleId: 'com.example.cozkazan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    appId: '1:846053857270:windows:XXXXXXXXXXXXXXXXXXXX',
    messagingSenderId: '846053857270',
    projectId: 'cozkazan-app',
    authDomain: 'cozkazan-app.firebaseapp.com',
    storageBucket: 'cozkazan-app.appspot.com',
  );
} 